const CATEGORY_MAP: Record<string, string> = {
  // ─── Carnes ───
  pollo: 'Carnes',
  'pechuga de pollo': 'Carnes',
  'muslos de pollo': 'Carnes',
  'alitas de pollo': 'Carnes',
  'contramuslos de pollo': 'Carnes',
  ternera: 'Carnes',
  'filetes de ternera': 'Carnes',
  'carne de ternera': 'Carnes',
  cerdo: 'Carnes',
  'lomo de cerdo': 'Carnes',
  'solomillo de cerdo': 'Carnes',
  'chuletas de cerdo': 'Carnes',
  'secreto iberico': 'Carnes',
  'presa iberica': 'Carnes',
  'pluma iberica': 'Carnes',
  jamon: 'Carnes',
  'jamon serrano': 'Carnes',
  'jamon iberico': 'Carnes',
  'jamon york': 'Carnes',
  'jamon cocido': 'Carnes',
  chorizo: 'Carnes',
  salchichas: 'Carnes',
  'salchichas frescas': 'Carnes',
  'salchichas frankfurt': 'Carnes',
  carne: 'Carnes',
  'carne picada': 'Carnes',
  'carne de cerdo': 'Carnes',
  'carne de pollo': 'Carnes',
  bacon: 'Carnes',
  panceta: 'Carnes',
  pavo: 'Carnes',
  'pechuga de pavo': 'Carnes',
  'fiambre de pavo': 'Carnes',
  lomo: 'Carnes',
  'lomo embuchado': 'Carnes',
  costillas: 'Carnes',
  morcilla: 'Carnes',
  lacon: 'Carnes',
  salchichon: 'Carnes',
  fuet: 'Carnes',
  mortadela: 'Carnes',
  sobrasada: 'Carnes',
  cecina: 'Carnes',
  bresaola: 'Carnes',
  pepperoni: 'Carnes',
  fiambre: 'Carnes',
  embutido: 'Carnes',
  cordero: 'Carnes',
  'chuletas de cordero': 'Carnes',
  conejo: 'Carnes',
  pato: 'Carnes',
  butifarra: 'Carnes',
  chistorra: 'Carnes',
  'hamburguesa': 'Carnes',
  'carne para guisar': 'Carnes',
  'solomillo': 'Carnes',
  'entrecot': 'Carnes',
  'chuleta': 'Carnes',
  'albondigas': 'Carnes',

  // ─── Pescados y Mariscos ───
  salmon: 'Pescados',
  'salmon ahumado': 'Pescados',
  atun: 'Pescados',
  'atun fresco': 'Pescados',
  merluza: 'Pescados',
  gambas: 'Pescados',
  'gambas peladas': 'Pescados',
  bacalao: 'Pescados',
  'bacalao desalado': 'Pescados',
  sardinas: 'Pescados',
  mejillones: 'Pescados',
  calamares: 'Pescados',
  calamar: 'Pescados',
  pulpo: 'Pescados',
  langostinos: 'Pescados',
  pescado: 'Pescados',
  dorada: 'Pescados',
  lubina: 'Pescados',
  rape: 'Pescados',
  'pez espada': 'Pescados',
  emperador: 'Pescados',
  trucha: 'Pescados',
  boquerones: 'Pescados',
  anchoas: 'Pescados',
  almejas: 'Pescados',
  berberechos: 'Pescados',
  sepia: 'Pescados',
  chirlas: 'Pescados',
  navajas: 'Pescados',
  'palitos de cangrejo': 'Pescados',
  surimi: 'Pescados',
  'colas de gamba': 'Pescados',
  vieiras: 'Pescados',
  cigalas: 'Pescados',
  percebes: 'Pescados',
  chipirones: 'Pescados',
  'pescadilla': 'Pescados',
  'rosada': 'Pescados',
  'lenguado': 'Pescados',
  'caballa': 'Pescados',
  'bonito': 'Pescados',

  // ─── Lácteos y Huevos ───
  leche: 'Lacteos',
  'leche entera': 'Lacteos',
  'leche desnatada': 'Lacteos',
  'leche semidesnatada': 'Lacteos',
  queso: 'Lacteos',
  'queso rallado': 'Lacteos',
  'queso parmesano': 'Lacteos',
  'queso manchego': 'Lacteos',
  'queso de cabra': 'Lacteos',
  'queso fresco': 'Lacteos',
  'queso cremoso': 'Lacteos',
  'queso cheddar': 'Lacteos',
  'queso emmental': 'Lacteos',
  'queso gouda': 'Lacteos',
  'queso brie': 'Lacteos',
  'queso roquefort': 'Lacteos',
  mozzarella: 'Lacteos',
  'queso feta': 'Lacteos',
  feta: 'Lacteos',
  parmesano: 'Lacteos',
  quesitos: 'Lacteos',
  'queso en lonchas': 'Lacteos',
  yogur: 'Lacteos',
  'yogur griego': 'Lacteos',
  'yogur natural': 'Lacteos',
  nata: 'Lacteos',
  'nata liquida': 'Lacteos',
  'nata montada': 'Lacteos',
  'nata para cocinar': 'Lacteos',
  mantequilla: 'Lacteos',
  huevos: 'Lacteos',
  huevo: 'Lacteos',
  'crema de leche': 'Lacteos',
  'leche condensada': 'Lacteos',
  'leche evaporada': 'Lacteos',
  ricotta: 'Lacteos',
  requesón: 'Lacteos',
  requeson: 'Lacteos',
  'queso Philadelphia': 'Lacteos',
  mascarpone: 'Lacteos',
  'bechamel': 'Lacteos',
  cuajada: 'Lacteos',
  natillas: 'Lacteos',
  'nata para montar': 'Lacteos',

  // ─── Verduras y Hortalizas ───
  tomate: 'Verduras',
  tomates: 'Verduras',
  'tomate cherry': 'Verduras',
  'tomates cherry': 'Verduras',
  'tomate pera': 'Verduras',
  'tomate raf': 'Verduras',
  cebolla: 'Verduras',
  'cebolla roja': 'Verduras',
  'cebolleta': 'Verduras',
  'cebolla morada': 'Verduras',
  ajo: 'Verduras',
  'dientes de ajo': 'Verduras',
  patatas: 'Verduras',
  patata: 'Verduras',
  'patatas fritas': 'Verduras',
  lechuga: 'Verduras',
  'lechuga iceberg': 'Verduras',
  'lechuga romana': 'Verduras',
  rucula: 'Verduras',
  canonigos: 'Verduras',
  'mezcla de lechugas': 'Verduras',
  pimiento: 'Verduras',
  pimientos: 'Verduras',
  'pimiento rojo': 'Verduras',
  'pimiento verde': 'Verduras',
  'pimiento amarillo': 'Verduras',
  'pimientos del piquillo': 'Verduras',
  'pimiento del padron': 'Verduras',
  zanahoria: 'Verduras',
  zanahorias: 'Verduras',
  calabacin: 'Verduras',
  calabacines: 'Verduras',
  berenjena: 'Verduras',
  berenjenas: 'Verduras',
  pepino: 'Verduras',
  pepinos: 'Verduras',
  champiñones: 'Verduras',
  champinones: 'Verduras',
  'champiñones laminados': 'Verduras',
  espinacas: 'Verduras',
  brocoli: 'Verduras',
  'brecol': 'Verduras',
  coliflor: 'Verduras',
  guisantes: 'Verduras',
  'guisantes congelados': 'Verduras',
  judias: 'Verduras',
  'judias verdes': 'Verduras',
  maiz: 'Verduras',
  'maiz dulce': 'Verduras',
  aceitunas: 'Verduras',
  'aceitunas negras': 'Verduras',
  'aceitunas verdes': 'Verduras',
  perejil: 'Verduras',
  cilantro: 'Verduras',
  eneldo: 'Verduras',
  alcachofa: 'Verduras',
  alcachofas: 'Verduras',
  esparragos: 'Verduras',
  'esparragos verdes': 'Verduras',
  'esparragos blancos': 'Verduras',
  'esparragos trigueros': 'Verduras',
  calabaza: 'Verduras',
  albahaca: 'Verduras',
  setas: 'Verduras',
  puerros: 'Verduras',
  puerro: 'Verduras',
  apio: 'Verduras',
  nabo: 'Verduras',
  rabano: 'Verduras',
  rabanos: 'Verduras',
  col: 'Verduras',
  'col lombarda': 'Verduras',
  lombarda: 'Verduras',
  repollo: 'Verduras',
  'coles de bruselas': 'Verduras',
  acelgas: 'Verduras',
  remolacha: 'Verduras',
  boniato: 'Verduras',
  jengibre: 'Verduras',
  'jengibre fresco': 'Verduras',
  menta: 'Verduras',
  romero: 'Verduras',
  tomillo: 'Verduras',
  laurel: 'Verduras',
  cebollino: 'Verduras',
  berros: 'Verduras',
  endivias: 'Verduras',
  hinojo: 'Verduras',
  'mezcla de verduras': 'Verduras',
  'verduras congeladas': 'Verduras',
  'pisto': 'Verduras',
  'menestra': 'Verduras',

  // ─── Frutas ───
  limon: 'Frutas',
  limones: 'Frutas',
  'zumo de limon': 'Frutas',
  aguacate: 'Frutas',
  aguacates: 'Frutas',
  platano: 'Frutas',
  platanos: 'Frutas',
  manzana: 'Frutas',
  manzanas: 'Frutas',
  naranja: 'Frutas',
  naranjas: 'Frutas',
  'zumo de naranja': 'Frutas',
  frutas: 'Frutas',
  fresa: 'Frutas',
  fresas: 'Frutas',
  melocoton: 'Frutas',
  pera: 'Frutas',
  peras: 'Frutas',
  uvas: 'Frutas',
  sandia: 'Frutas',
  melon: 'Frutas',
  piña: 'Frutas',
  pina: 'Frutas',
  kiwi: 'Frutas',
  mango: 'Frutas',
  mandarina: 'Frutas',
  mandarinas: 'Frutas',
  cereza: 'Frutas',
  cerezas: 'Frutas',
  ciruela: 'Frutas',
  ciruelas: 'Frutas',
  higos: 'Frutas',
  granada: 'Frutas',
  papaya: 'Frutas',
  frambuesas: 'Frutas',
  arandanos: 'Frutas',
  coco: 'Frutas',
  'coco rallado': 'Frutas',
  lima: 'Frutas',
  pomelo: 'Frutas',
  'frutos rojos': 'Frutas',
  pasas: 'Frutas',
  datiles: 'Frutas',

  // ─── Bebidas ───
  'leche de coco': 'Bebidas',
  'leche de avena': 'Bebidas',
  'leche de almendras': 'Bebidas',
  'leche de soja': 'Bebidas',
  'bebida vegetal': 'Bebidas',
  zumo: 'Bebidas',
  agua: 'Bebidas',
  cerveza: 'Bebidas',
  vino: 'Bebidas',
  'vino blanco': 'Bebidas',
  'vino tinto': 'Bebidas',
  cava: 'Bebidas',
  sidra: 'Bebidas',
  'agua con gas': 'Bebidas',
  cafe: 'Bebidas',
  te: 'Bebidas',
  'infusion': 'Bebidas',

  // ─── Pasta y Cereales ───
  macarrones: 'Pasta y Cereales',
  espaguetis: 'Pasta y Cereales',
  pasta: 'Pasta y Cereales',
  tallarines: 'Pasta y Cereales',
  fideos: 'Pasta y Cereales',
  'fideos chinos': 'Pasta y Cereales',
  lasaña: 'Pasta y Cereales',
  'placas de lasaña': 'Pasta y Cereales',
  canelones: 'Pasta y Cereales',
  ravioli: 'Pasta y Cereales',
  ñoquis: 'Pasta y Cereales',
  noquis: 'Pasta y Cereales',
  penne: 'Pasta y Cereales',
  fusilli: 'Pasta y Cereales',
  'pasta fresca': 'Pasta y Cereales',
  arroz: 'Pasta y Cereales',
  'arroz basmati': 'Pasta y Cereales',
  'arroz integral': 'Pasta y Cereales',
  'arroz redondo': 'Pasta y Cereales',
  'arroz bomba': 'Pasta y Cereales',
  pan: 'Pasta y Cereales',
  'pan rallado': 'Pasta y Cereales',
  'pan tostado': 'Pasta y Cereales',
  'pan de hamburguesa': 'Pasta y Cereales',
  'pan de molde': 'Pasta y Cereales',
  'pan integral': 'Pasta y Cereales',
  'pan de pita': 'Pasta y Cereales',
  baguette: 'Pasta y Cereales',
  chapata: 'Pasta y Cereales',
  cuscus: 'Pasta y Cereales',
  quinoa: 'Pasta y Cereales',
  bulgur: 'Pasta y Cereales',
  granola: 'Pasta y Cereales',
  cereales: 'Pasta y Cereales',
  avena: 'Pasta y Cereales',
  'copos de avena': 'Pasta y Cereales',
  muesli: 'Pasta y Cereales',
  'tortillas de maiz': 'Pasta y Cereales',
  harina: 'Pasta y Cereales',
  'harina de trigo': 'Pasta y Cereales',
  'harina de maiz': 'Pasta y Cereales',
  'maizena': 'Pasta y Cereales',
  tortillas: 'Pasta y Cereales',
  'tortillas de trigo': 'Pasta y Cereales',
  'masa de pizza': 'Pasta y Cereales',
  'masa de hojaldre': 'Pasta y Cereales',
  'masa brisa': 'Pasta y Cereales',
  'masa quebrada': 'Pasta y Cereales',
  'masa filo': 'Pasta y Cereales',
  galletas: 'Pasta y Cereales',
  'tostadas': 'Pasta y Cereales',
  'crackers': 'Pasta y Cereales',
  'colines': 'Pasta y Cereales',
  'picos': 'Pasta y Cereales',

  // ─── Conservas y Legumbres ───
  'tomate frito': 'Conservas',
  'tomate triturado': 'Conservas',
  'salsa de tomate': 'Conservas',
  'tomate natural triturado': 'Conservas',
  'atun en lata': 'Conservas',
  'atun en aceite': 'Conservas',
  'sardinas en lata': 'Conservas',
  garbanzos: 'Conservas',
  'garbanzos cocidos': 'Conservas',
  lentejas: 'Conservas',
  'lentejas cocidas': 'Conservas',
  alubias: 'Conservas',
  'alubias blancas': 'Conservas',
  'judiones': 'Conservas',
  fabes: 'Conservas',
  'frijoles': 'Conservas',
  'alubias rojas': 'Conservas',
  'judias pintas': 'Conservas',
  'guisantes en lata': 'Conservas',
  'maiz en lata': 'Conservas',
  'pimientos del piquillo en lata': 'Conservas',
  'esparragos en lata': 'Conservas',
  'caldo de pollo': 'Conservas',
  'caldo de verduras': 'Conservas',
  'caldo de carne': 'Conservas',
  'caldo': 'Conservas',
  'pastillas de caldo': 'Conservas',
  'leche de coco en lata': 'Conservas',
  'pisto en lata': 'Conservas',
  'mermelada': 'Conservas',
  'miel': 'Conservas',
  'aceitunas en lata': 'Conservas',
  'frutos secos': 'Conservas',
  almendras: 'Conservas',
  nueces: 'Conservas',
  cacahuetes: 'Conservas',
  pipas: 'Conservas',
  pistachos: 'Conservas',
  avellanas: 'Conservas',
  anacardos: 'Conservas',
  pinones: 'Conservas',

  // ─── Especias y Condimentos ───
  sal: 'Especias y Condimentos',
  pimienta: 'Especias y Condimentos',
  'pimienta negra': 'Especias y Condimentos',
  oregano: 'Especias y Condimentos',
  comino: 'Especias y Condimentos',
  pimenton: 'Especias y Condimentos',
  'pimenton dulce': 'Especias y Condimentos',
  'pimenton de la vera': 'Especias y Condimentos',
  'pimenton picante': 'Especias y Condimentos',
  curry: 'Especias y Condimentos',
  canela: 'Especias y Condimentos',
  'canela en polvo': 'Especias y Condimentos',
  nuez_moscada: 'Especias y Condimentos',
  'nuez moscada': 'Especias y Condimentos',
  guindilla: 'Especias y Condimentos',
  cayena: 'Especias y Condimentos',
  azafran: 'Especias y Condimentos',
  curcuma: 'Especias y Condimentos',
  salsa: 'Especias y Condimentos',
  'salsa de soja': 'Especias y Condimentos',
  'salsa worcestershire': 'Especias y Condimentos',
  'salsa barbacoa': 'Especias y Condimentos',
  'salsa teriyaki': 'Especias y Condimentos',
  'salsa pesto': 'Especias y Condimentos',
  'salsa cesar': 'Especias y Condimentos',
  mayonesa: 'Especias y Condimentos',
  mostaza: 'Especias y Condimentos',
  ketchup: 'Especias y Condimentos',
  vinagre: 'Especias y Condimentos',
  'vinagre de vino': 'Especias y Condimentos',
  'vinagre de manzana': 'Especias y Condimentos',
  'vinagre balsamico': 'Especias y Condimentos',
  'aceite de oliva': 'Especias y Condimentos',
  'aceite de oliva virgen extra': 'Especias y Condimentos',
  'aceite de girasol': 'Especias y Condimentos',
  aceite: 'Especias y Condimentos',
  azucar: 'Especias y Condimentos',
  'azucar moreno': 'Especias y Condimentos',
  'levadura': 'Especias y Condimentos',
  'levadura fresca': 'Especias y Condimentos',
  'bicarbonato': 'Especias y Condimentos',
  'extracto de vainilla': 'Especias y Condimentos',
  'cacao en polvo': 'Especias y Condimentos',
  chocolate: 'Especias y Condimentos',
  'chocolate negro': 'Especias y Condimentos',
  'chips de chocolate': 'Especias y Condimentos',
  'hierbas provenzales': 'Especias y Condimentos',
  'ajo en polvo': 'Especias y Condimentos',
  'cebolla en polvo': 'Especias y Condimentos',
  'especias': 'Especias y Condimentos',
  'tahini': 'Especias y Condimentos',
  'hummus': 'Especias y Condimentos',
  'guacamole': 'Especias y Condimentos',
  'sriracha': 'Especias y Condimentos',
  'tabasco': 'Especias y Condimentos',
}

export const CATEGORIES = [
  'Carnes',
  'Pescados',
  'Lacteos',
  'Verduras',
  'Frutas',
  'Bebidas',
  'Pasta y Cereales',
  'Conservas',
  'Especias y Condimentos',
  'Otros',
] as const

export const CATEGORY_META: Record<string, { color: string; bgColor: string; icon: string }> = {
  'Carnes':                 { color: 'text-red-600',    bgColor: 'bg-red-50',    icon: 'beef' },
  'Pescados':               { color: 'text-blue-600',   bgColor: 'bg-blue-50',   icon: 'fish' },
  'Lacteos':                { color: 'text-amber-700',  bgColor: 'bg-amber-50',  icon: 'milk' },
  'Verduras':               { color: 'text-green-600',  bgColor: 'bg-green-50',  icon: 'leaf' },
  'Frutas':                 { color: 'text-yellow-600', bgColor: 'bg-yellow-50', icon: 'apple' },
  'Bebidas':                { color: 'text-purple-600', bgColor: 'bg-purple-50', icon: 'glass-water' },
  'Pasta y Cereales':       { color: 'text-orange-700', bgColor: 'bg-orange-50', icon: 'wheat' },
  'Conservas':              { color: 'text-slate-600',  bgColor: 'bg-slate-50',  icon: 'package' },
  'Especias y Condimentos': { color: 'text-orange-600', bgColor: 'bg-orange-50', icon: 'flame' },
  'Otros':                  { color: 'text-slate-500',  bgColor: 'bg-slate-50',  icon: 'circle' },
}

export function getCategory(ingredientName: string): string {
  const normalized = ingredientName.trim().toLowerCase()

  // Exact match first
  if (CATEGORY_MAP[normalized]) return CATEGORY_MAP[normalized]

  // Partial match: check if the ingredient contains a known key
  for (const [key, category] of Object.entries(CATEGORY_MAP)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return category
    }
  }

  return 'Otros'
}
